table Dim_Customers
	lineageTag: 50f0c4c7-a7fb-4ab3-8e08-2d53395f6daa

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: 638715bf-1847-40ab-9c97-85c249cf6cf0
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'First Name'
		dataType: string
		lineageTag: 2683d9c4-af4b-4b77-afbc-9e09ebf1ce14
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Last Name'
		dataType: string
		lineageTag: 6ce55020-b072-4087-806b-09e7f0aa9ff7
		summarizeBy: none
		sourceColumn: Last Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 760c9a3d-956e-4f4b-adb0-1d11284c81bd
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Street
		dataType: string
		lineageTag: 7b75d2e5-814b-4418-a6cc-37217777e3ab
		summarizeBy: none
		sourceColumn: Street

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 8f733af0-0e1a-4692-af83-06585e617cac
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: bffe3d8b-59a1-43e2-ba68-03f70d65d812
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: ad600f84-a3f8-43c2-9766-d5bdb034d714
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Zip code'
		dataType: string
		lineageTag: aca31f95-76ca-4f94-9fa8-7eb142d5a4a9
		summarizeBy: none
		sourceColumn: Zip code

		annotation SummarizationSetBy = Automatic

	partition Dim_Customers = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database(DB_Server, DB_Name),
				  #"Navigation 1" = Source{[Schema = "core", Item = "dim_customers"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Navigation 1",{{"last_name", "Last Name"}, {"city", "City"}, {"country", "Country"}, {"first_name", "First Name"}, {"segment", "Segment"}, {"state", "State"}, {"street", "Street"}, {"zipcode", "Zip code"}, {"customer_id", "Customer ID"}})
				in
				  #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

