table Dim_Geography
	lineageTag: 09fc82a2-4f4d-4ef4-b732-8eafd6cc7ecb

	column geo_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a220f54a-4bc0-4465-bdb5-b3102d9a72be
		summarizeBy: none
		sourceColumn: geo_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Region'
		dataType: string
		lineageTag: 5934a282-7eb3-4be7-b72e-b51cd9702956
		summarizeBy: none
		sourceColumn: Order Region

		annotation SummarizationSetBy = Automatic

	column 'Order Country'
		dataType: string
		lineageTag: eaf0da0f-16ab-423f-b291-aa9bf523172e
		summarizeBy: none
		sourceColumn: Order Country

		annotation SummarizationSetBy = Automatic

	column 'Order State'
		dataType: string
		lineageTag: 21a01be3-eeb4-44c4-92f3-37612bf2e2fc
		summarizeBy: none
		sourceColumn: Order State

		annotation SummarizationSetBy = Automatic

	column 'Order City'
		dataType: string
		lineageTag: 9485a434-13df-44ab-8a23-44bb033cb426
		summarizeBy: none
		sourceColumn: Order City

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 0e42f318-005b-48ca-98cf-1afd571b7cc4
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	partition Dim_Geography = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database(DB_Server, DB_Name),
				  #"Navigation 1" = Source{[Schema = "core", Item = "dim_geography"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Navigation 1",{{"order_region", "Order Region"}, {"market", "Market"}, {"order_city", "Order City"}, {"order_country", "Order Country"}, {"order_state", "Order State"}})
				in
				  #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

