table Dim_Shipping
	lineageTag: 1b17351f-2bb4-45d7-b3ad-8ea66d0bf305

	column shipping_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 28de3eaf-65ea-4380-b6a3-461a8a4693a4
		summarizeBy: none
		sourceColumn: shipping_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Shipping Mode'
		dataType: string
		lineageTag: a236df32-6b00-45b9-85e4-285761ce3c3e
		summarizeBy: none
		sourceColumn: Shipping Mode

		annotation SummarizationSetBy = Automatic

	column 'Delivery Status'
		dataType: string
		lineageTag: 683090e8-a621-4efd-8237-ecc4191922d0
		summarizeBy: none
		sourceColumn: Delivery Status

		annotation SummarizationSetBy = Automatic

	column 'Late Delivery Risk'
		dataType: int64
		formatString: 0
		lineageTag: d662d98d-dd20-4df6-9174-e92313b3abb6
		summarizeBy: none
		sourceColumn: Late Delivery Risk

		annotation SummarizationSetBy = Automatic

	partition Dim_Shipping = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database(DB_Server, DB_Name),
				  #"Navigation 1" = Source{[Schema = "core", Item = "dim_shipping"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Navigation 1",{{"shipping_mode", "Shipping Mode"}, {"delivery_status", "Delivery Status"}, {"late_delivery_risk", "Late Delivery Risk"}})
				in
				  #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

